import builtins from 'builtin-modules';
import esbuild from 'esbuild';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const isWatch = process.argv[2] === 'watch';

/** @type Promise<Promise<esbuild.BuildContext<esbuild.BuildOptions>>> */
const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ['src/ts/background.ts', 'src/ts/contentScript.ts', 'src/ts/options.ts'],
  outdir: 'dist/js/',
  bundle: true,
  external: [
    ...builtins
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod
});

try {
  await context.rebuild();
  console.log(`⚡ Finished generating ${prod ? 'production' : 'development'} build of task calendar! ⚡`);
  if (isWatch) {
    await context.watch();
  }
} catch (error) {
  process.exit(1);
} finally {
  process.exit(0);
}
