name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build/build.sh

      - name: Upload Chrome Extension (crx)
        uses: actions/upload-artifact@v3
        with:
          name: bypass-paywalls.crx
          path: |
            dist/bypass-paywalls.crx

      - name: Upload Firefox Extension (xpi)
        uses: actions/upload-artifact@v3
        with:
          name: bypass-paywalls.xpi
          path: |
            dist/bypass-paywalls.xpi
